services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: greyb_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html/app
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: greyb_app_db
    environment:
      POSTGRES_DB: greyb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
